const Message=require("../models/Message"),User=require("../models/User"),Conversation=require("../models/Conversation");
const buildMedia=(file)=>{if(!file)return undefined;const b64=file.buffer.toString("base64");const type=file.mimetype.startsWith("image")?"image":file.mimetype.startsWith("video")?"video":"document";return{data:`data:${file.mimetype};base64,${b64}`,mimeType:file.mimetype,type,filename:file.originalname,size:file.size};};
exports.getConversations=async(req,res)=>{try{const me=await User.findById(req.user.id).populate("connections","name username avatarUrl headline lastSeen hideOnlineStatus");const conversations=await Promise.all(me.connections.map(async conn=>{const lastMsg=await Message.findOne({$or:[{sender:req.user.id,receiver:conn._id},{sender:conn._id,receiver:req.user.id}]}).sort({createdAt:-1});const unread=await Message.countDocuments({sender:conn._id,receiver:req.user.id,read:false});return{user:conn,lastMessage:lastMsg,unread};}));conversations.sort((a,b)=>new Date(b.lastMessage?.createdAt||0)-new Date(a.lastMessage?.createdAt||0));res.json({success:true,conversations});}catch(e){res.status(500).json({success:false,message:"Server Error"});}};
exports.getMessages=async(req,res)=>{try{const{userId}=req.params;const messages=await Message.find({$or:[{sender:req.user.id,receiver:userId},{sender:userId,receiver:req.user.id}]}).sort({createdAt:1}).populate("sender","name username avatarUrl");await Message.updateMany({sender:userId,receiver:req.user.id,read:false},{read:true});res.json({success:true,messages});}catch(e){res.status(500).json({success:false,message:"Server Error"});}};
exports.sendMessage=async(req,res)=>{try{const{text}=req.body,{userId}=req.params;const media=buildMedia(req.file);if(!text?.trim()&&!media)return res.status(400).json({success:false,message:"Message required"});const message=await Message.create({sender:req.user.id,receiver:userId,text:text?.trim()||"",media});await message.populate("sender","name username avatarUrl");res.status(201).json({success:true,message});}catch(e){res.status(500).json({success:false,message:"Server Error"});}};

exports.clearMessages=async(req,res)=>{try{const{userId}=req.params;await Message.deleteMany({$or:[{sender:req.user.id,receiver:userId},{sender:userId,receiver:req.user.id}]});res.json({success:true,message:"Chat cleared"});}catch(e){res.status(500).json({success:false,message:"Server Error"});}};

exports.createGroup=async(req,res)=>{try{const{name,memberIds}=req.body;if(!name?.trim())return res.status(400).json({success:false,message:"Group name required"});const ids=Array.isArray(memberIds)?memberIds.filter(id=>id&&id!==req.user.id):[];const participants=[req.user.id,...new Set(ids)];if(participants.length<3)return res.status(400).json({success:false,message:"Select at least 2 members"});const conversation=await Conversation.create({name:name.trim(),participants,createdBy:req.user.id});await conversation.populate("participants","name username avatarUrl");res.status(201).json({success:true,conversation});}catch(e){res.status(500).json({success:false,message:"Server Error"});}};

exports.getGroupConversations=async(req,res)=>{try{const convs=await Conversation.find({participants:req.user.id}).populate("participants","name username avatarUrl headline");const conversations=await Promise.all(convs.map(async c=>{const lastMessage=await Message.findOne({conversation:c._id}).sort({createdAt:-1}).populate("sender","name");const unread=await Message.countDocuments({conversation:c._id,sender:{$ne:req.user.id},readBy:{$ne:req.user.id}});return{conversation:c,lastMessage,unread};}));conversations.sort((a,b)=>new Date(b.lastMessage?.createdAt||0)-new Date(a.lastMessage?.createdAt||0));res.json({success:true,conversations});}catch(e){res.status(500).json({success:false,message:"Server Error"});}};

exports.getGroupMessages=async(req,res)=>{try{const{conversationId}=req.params;const conv=await Conversation.findOne({_id:conversationId,participants:req.user.id});if(!conv)return res.status(404).json({success:false,message:"Conversation not found"});const messages=await Message.find({conversation:conversationId}).sort({createdAt:1}).populate("sender","name username avatarUrl");await Message.updateMany({conversation:conversationId,sender:{$ne:req.user.id}},{$addToSet:{readBy:req.user.id}});res.json({success:true,messages});}catch(e){res.status(500).json({success:false,message:"Server Error"});}};

exports.sendGroupMessage=async(req,res)=>{try{const{text}=req.body,{conversationId}=req.params;const media=buildMedia(req.file);if(!text?.trim()&&!media)return res.status(400).json({success:false,message:"Message required"});const conv=await Conversation.findOne({_id:conversationId,participants:req.user.id});if(!conv)return res.status(404).json({success:false,message:"Conversation not found"});const message=await Message.create({sender:req.user.id,conversation:conversationId,text:text?.trim()||"",media,readBy:[req.user.id]});await message.populate("sender","name username avatarUrl");res.status(201).json({success:true,message});}catch(e){res.status(500).json({success:false,message:"Server Error"});}};

exports.clearGroupMessages=async(req,res)=>{try{const{conversationId}=req.params;const conv=await Conversation.findOne({_id:conversationId,participants:req.user.id});if(!conv)return res.status(404).json({success:false,message:"Conversation not found"});await Message.deleteMany({conversation:conversationId});res.json({success:true,message:"Chat cleared"});}catch(e){res.status(500).json({success:false,message:"Server Error"});}};

exports.leaveGroup=async(req,res)=>{try{const{conversationId}=req.params;const conv=await Conversation.findOne({_id:conversationId,participants:req.user.id});if(!conv)return res.status(404).json({success:false,message:"Conversation not found"});conv.participants=conv.participants.filter(p=>p.toString()!==req.user.id);await conv.save();res.json({success:true,message:"Left group"});}catch(e){res.status(500).json({success:false,message:"Server Error"});}};
