const User=require("../models/User"),Connection=require("../models/Connection"),Notification=require("../models/Notification");

exports.getSuggestions=async(req,res)=>{try{const me=await User.findById(req.user.id);const exc=[req.user.id,...me.connections];const users=await User.find({_id:{$nin:exc}}).select("name username headline avatarUrl location connections skills").limit(10);res.json({success:true,users});}catch(e){res.status(500).json({success:false,message:"Server Error"});}};
exports.getConnections=async(req,res)=>{try{const user=await User.findById(req.user.id).populate("connections","name username headline avatarUrl location skills");res.json({success:true,connections:user.connections});}catch(e){res.status(500).json({success:false,message:"Server Error"});}};
exports.sendRequest=async(req,res)=>{try{const{userId}=req.params;if(userId===req.user.id)return res.status(400).json({success:false,message:"Cannot connect with yourself"});const exists=await Connection.findOne({requester:req.user.id,recipient:userId});if(exists)return res.status(400).json({success:false,message:"Request already sent"});await Connection.create({requester:req.user.id,recipient:userId});const sender=await User.findById(req.user.id).select("name");await Notification.create({recipient:userId,sender:req.user.id,type:"connection",message:`${sender.name} sent you a connection request`,link:"/network"});res.status(201).json({success:true,message:"Request sent"});}catch(e){res.status(500).json({success:false,message:"Server Error"});}};
exports.getRequests=async(req,res)=>{try{const requests=await Connection.find({recipient:req.user.id,status:"pending"}).populate("requester","name username headline avatarUrl location connections");res.json({success:true,requests});}catch(e){res.status(500).json({success:false,message:"Server Error"});}};
exports.acceptRequest=async(req,res)=>{try{const conn=await Connection.findById(req.params.id);if(!conn||conn.recipient.toString()!==req.user.id)return res.status(403).json({success:false,message:"Not authorized"});conn.status="accepted";await conn.save();await User.findByIdAndUpdate(req.user.id,{$addToSet:{connections:conn.requester}});await User.findByIdAndUpdate(conn.requester,{$addToSet:{connections:req.user.id}});await Notification.create({recipient:conn.requester,sender:req.user.id,type:"connection",message:"accepted your connection request",link:"/network"});res.json({success:true,message:"Connection accepted"});}catch(e){res.status(500).json({success:false,message:"Server Error"});}};
exports.rejectRequest=async(req,res)=>{try{const conn=await Connection.findById(req.params.id);if(!conn)return res.status(404).json({success:false,message:"Not found"});conn.status="rejected";await conn.save();res.json({success:true,message:"Rejected"});}catch(e){res.status(500).json({success:false,message:"Server Error"});}};
exports.removeConnection=async(req,res)=>{try{const{userId}=req.params;await User.findByIdAndUpdate(req.user.id,{$pull:{connections:userId}});await User.findByIdAndUpdate(userId,{$pull:{connections:req.user.id}});await Connection.deleteOne({$or:[{requester:req.user.id,recipient:userId},{requester:userId,recipient:req.user.id}]});res.json({success:true,message:"Removed"});}catch(e){res.status(500).json({success:false,message:"Server Error"});}};
